# Site settings
title: "Rob Wilson"
author: "Rob Wilson"
keywords: "phobos, phobos101, node, mean, javascript, Rob Wilson"
email: "robwilson101@gmail.com"
description: "Personal website of Rob Wilson. Showcasing projects and writing blog entries."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://phobos101.github.io/" # the base hostname & protocol for your site
twitter_username: "phobos101"
github_username:  "phobos101"
favicon: "/images/favicon.ico"
syntax-highlight: True

# Build settings
# markdown: kramdown
