
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://phobos101.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /

# Google tracking id to track your visitors

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Rob Wilson"
title: "Rob Wilson - Web Developer"
description: "Personal website of Rob Wilson. Showcasing projects and writing blog entries."
keywords: "phobos, phobos101, node, mean, javascript"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Hi, my name is Rob."
  - text: "I make web apps, and I never stop learning."

me-img: "/img/headshot_1-min.jpg"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/wdi16-min.jpg"
    date: "September 2015 - December 2015"
    description: "Full time web development student at General Assembly"
  - image: "/img/timeline/default.png"
    date: "Febuary 2015 - September 2015"
    description: "Started hobby programming in Python"
  - image: "/img/timeline/cisco-min.jpg"
    date: "June 2013 - September 2015"
    description: "Worked for the Cisco CNG as a network support engineer"
  - image: "/img/timeline/roadtrip-min.jpg"
    date: "May 2013 - July 2013"
    description: "Road trip down USA route 101 - Washington through to Arizona (with 2 weeks in San Francisco for job training!)"
  - image: "/img/timeline/graduation-min.jpg"
    date: "September 2009 - May 2013"
    description: "4 years at Staffordshire University"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "robwilson101@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/phobos101"
  - title: "github"
    url: "https://github.com/phobos101"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Projects: 'projects'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
